### ISSUE TITLE
Update DB and checksum download URLs

### ISSUE THREAD

**Issue by HelloHungryImDad** [bartbutenaers/node-red-contrib-ip-location-lite#4]
The URLs for GeoIP don't seem to work any more. I found that in `updatedb.js` I had to substitute `geoip.maxwind.com` for `download.maxwind.com` in all URLs and `suffix=zip.md5` to `suffix=zip.sha256` in the checksum URLs for the update to work.

**Comment by bartbutenaers** [comment]
Hi @HelloHungryImDad,
Thanks a lot for investigating this on your own!

However the [update.js](https://github.com/geoip-lite/node-geoip/blob/main/scripts/updatedb.js) file is part of the [node-geoip](https://github.com/geoip-lite/node-geoip) project.  It would be nice if you could create an issue for their Github repository (and add a link to it here).  Once they have updated the js file based on your feedback, it will be fixed here automatically since that library is used here as an npm dependeny.

Kind regards,
Bart

**Comment by HelloHungryImDad** [comment]
Apologies, I didn't follow the chain of dependencies properly! Thank you for making this library.

I've raised an [issue](https://github.com/geoip-lite/node-geoip/issues/235) and a [pull request](https://github.com/geoip-lite/node-geoip/pull/234) upstream.

**Comment by bartbutenaers** [comment]
No apologies required!  It is nice to see that you implemented the solution yourself.
Thanks for the link also!!

**Comment by HelloHungryImDad** [comment]
This has now been patched upstream. I'll close this issue. Thanks again!
